<script setup lang="ts"></script>

<template>
  <q-page>
    <div class="column q-pa-md q-gutter-x-sm">
      <q-btn
        href="https://quasar.dev/layout/grid/introduction-to-flexbox"
        icon="mdi-format-align-center"
        label="Flexbox"
        target="_blank"
      />
      <q-btn
        href="https://quasar.dev/vue-components/badge"
        icon="mdi-police-badge-outline"
        label="Badge"
        target="_blank"
      />
      <q-btn
        href="https://quasar.dev/vue-components/banner"
        icon="mdi-alpha-b-box-outline"
        label="Banner"
        target="_blank"
      />
      <q-btn
        href="https://quasar.dev/vue-components/button"
        icon="mdi-gesture-tap-button"
        label="Button"
        target="_blank"
      />
      <q-btn
        href="https://quasar.dev/vue-components/card"
        icon="mdi-card-account-details-outline"
        label="Card"
        target="_blank"
      />
      <q-btn
        href="https://quasar.dev/vue-components/carousel"
        icon="mdi-view-carousel-outline"
        label="Carousel"
        target="_blank"
      />
      <q-btn
        href="https://quasar.dev/vue-components/checkbox"
        icon="mdi-checkbox-outline"
        label="Checkbox"
        target="_blank"
      />
      <q-btn
        href="https://quasar.dev/vue-components/img"
        icon="mdi-camera-image"
        label="Img"
        target="_blank"
      />
      <q-btn
        href="https://quasar.dev/vue-components/input"
        icon="mdi-import"
        label="Input"
        target="_blank"
      />
      <q-btn
        href="https://quasar.dev/vue-components/radio"
        icon="mdi-radiobox-marked"
        label="Radio"
        target="_blank"
      />
      <q-btn
        href="https://quasar.dev/vue-components/select"
        icon="mdi-form-dropdown"
        label="Select"
        target="_blank"
      />
      <q-btn
        href="https://quasar.dev/style/"
        icon="mdi-palette-swatch-variant"
        label="Style & Identity"
        target="_blank"
      />
      <q-btn
        href="https://quasar.dev/vue-components/table"
        icon="mdi-table-large"
        label="Table"
        target="_blank"
      />
      <q-btn
        href="https://fonts.google.com/icons"
        icon="mdi-material-design"
        label="Material Icons Library (Google)"
        target="_blank"
      />
      <q-btn
        href="https://materialdesignicons.com/"
        icon="mdi-vector-square"
        label="Material Design Icons"
        target="_blank"
      />
    </div>
  </q-page>
</template>

<style scoped></style>
